### ISSUE TITLE
Upstream change Linux/Mac release tarball to tar.gz

### ISSUE THREAD

**Issue by czchen** [adamcrews/asdf-tf-summarize#5]
**Describe the bug**

Upstream release tarball has been changed to tar.gz for Linux/Mac.

**Steps to reproduce**

* Run `asdf install tf-summarize 0.3.6` in Linux/Mac.
* Has the following error:

```
$ asdf install tf-summarize 0.3.6
* Downloading tf-summarize release 0.3.6...
curl: (22) The requested URL returned error: 404
asdf-tf-summarize: Could not download https://github.com/dineshba/tf-summarize/releases/download/v0.3.6/tf-summarize_linux_amd64.zip
```

**Expected behavior**

tf-summarize shall be installed successful.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by adamcrews** [comment]
Thanks for the report, I'm sorry I missed this way back in november.
This is resolved with https://github.com/adamcrews/asdf-tf-summarize/pull/6, and released now as v0.1.1
